name: Share Kubectl Version Between Jobs

on:
  push:
    branches:
      - main

jobs:
  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract Kubectl version from Dockerfile
        id: extract_kubectl_version
        run: |
          KUBECTL_VERSION=$(grep -oP '(?<=KUBECTL_VERSION=)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          echo "KUBECTL_VERSION=$KUBECTL_VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$KUBECTL_VERSION"  # Define a saída chamada 'version' com o valor da versão
      - name: Upload Kubectl version artifact
        uses: actions/upload-artifact@v2
        with:
          name: kubectl-version
          path: .  # Você pode carregar qualquer arquivo que deseja compartilhar aqui

  use-version:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Download Kubectl version artifact
        uses: actions/download-artifact@v2
        with:
          name: kubectl-version
      - name: Show Kubectl version
        run: echo "Kubectl version is ${{ needs.extract-version.outputs.version }}"  # Mostra o valor da versão compartilhada
