name: Share Kubectl Version Between Jobs

on:
  push:
    branches:
      - main

jobs:
  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Kubectl version from Dockerfile
        id: extract_kubectl_version
        run: echo "KUBECTL_VERSION=$(grep -oP '(?<=KUBECTL_VERSION=)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)" >> $GITHUB_ENV
      - name: Upload Kubectl version artifact
        uses: actions/upload-artifact@v2
        with:
          name: kubectl-version
          path: .  # You can upload any files you want to share here

  use-version:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Download Kubectl version artifact
        uses: actions/download-artifact@v2
        with:
          name: kubectl-version
      - name: Show Kubectl version
        run: echo "Kubectl version is $KUBECTL_VERSION"
