name: Workflow Outputs

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"

  job2:
    runs-on: ubuntu-latest
    # Wait for job1 to be completed before starting job2
    needs: job1
    env:
      OUTPUT1: ${{ needs.job1.outputs.output1 }}
      OUTPUT2: ${{ needs.job1.outputs.output2 }}
    steps:
    - name: Access output variables
      run: echo $OUTPUT1 $OUTPUT2
