name: Build Kubectl

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

permissions: write-all


jobs:
  login-repo:
    name: Login in Docker Hub and GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  # build-and-push:
  #   name: Build and Push Image in Docker Hub and GitHub Container Registry
  #   runs-on: ubuntu-latest
  #   needs: login-repo
  #   steps:
      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: emanuelfds/kubectl:1.29.2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # caminho para o Dockerfile
          push: true
          tags: emanuelfds/kubectl:1.29.2

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/emanuelfds/kubectl:1.29.2
