name: Workflow Outputs

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    # Define environment variables
    env:
      OUTPUT1: hello
      OUTPUT2: world
    steps:
    - name: Output variable1
      run: echo "OUTPUT1=${OUTPUT1}" >> $GITHUB_ENV
    - name: Output variable2
      run: echo "OUTPUT2=${OUTPUT2}" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    # Wait from the job1 to be completed before starting job2
    needs: job1
    steps:
    - name: Access output variables
      run: echo $OUTPUT1 $OUTPUT2
