name: Build Kubectl

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

permissions: write-all

jobs:
  login-repo:
    name: Build and Push Image in Docker Hub and GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Kubectl version from Dockerfile
        id: extract_kubectl_version
        run: |
          export KUBECTL_VERSION=$(grep -oP '(?<=KUBECTL_VERSION=)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          echo "KUBECTL_VERSION=$KUBECTL_VERSION" >> $GITHUB_ENV

      - name: Show Kubectl version
        run: echo "Extracted version is ${{ env.KUBECTL_VERSION }}"

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: emanuelfds/kubectl:${{ steps.extract_kubectl_version.outputs.KUBECTL_VERSION }}

      - name: Build and Push Image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/emanuelfds/kubectl:${{ steps.extract_kubectl_version.outputs.KUBECTL_VERSION }}

  trivy-scanning-dockerhub:
    name: Trivy Scanner for Docker Hub
    needs: login-repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Kubectl version for Docker Hub scan
        run: echo "KUBECTL_VERSION=${{ steps.login-repo.outputs.KUBECTL_VERSION }}" >> $GITHUB_ENV

      - name: Trivy Scan Docker Hub
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'emanuelfds/kubectl:${{ env.KUBECTL_VERSION }}'
          format: 'sarif'
          output: 'trivy-results-dockerhub.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-dockerhub.sarif'

  trivy-scanning-ghcr:
    name: Trivy Scanner for GitHub Container Registry
    needs: login-repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Kubectl version for GitHub Container Registry scan
        run: echo "KUBECTL_VERSION=${{ steps.login-repo.outputs.KUBECTL_VERSION }}" >> $GITHUB_ENV

      - name: Trivy Scan GitHub Container Registry
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/emanuelfds/kubectl:${{ env.KUBECTL_VERSION }}'
          format: 'sarif'
          output: 'trivy-results-ghcr.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-ghcr.sarif'
